spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:4444/order-service
    username: pisethsattya
    password: microservice
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081

inventory:
  url: http://localhost:8082

springdoc:
  swagger-ui:
    path: docs
  api-docs:
    path: /api-docs

# Resilient4j Properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true  # Enables health indicator for this circuit breaker
        event-consumer-buffer-size: 10   # Number of events stored in the event consumer
        sliding-window-type: count_based # Type of sliding window (can be time-based or count-based)
        sliding-window-size: 5           # Number of calls in the sliding window
        failure-rate-threshold: 50       # Percentage of failed calls to trigger circuit breaker
        wait-duration-in-open-state:     # How long the circuit breaker stays open before transitioning to half-open
          seconds: 5                     # Duration in seconds
        permitted-number-of-calls-in-half-open-state: 3  # Number of allowed calls when circuit breaker is half-open
        automatic-transition-from-open-to-half-open-enabled: true # Automatically transition from open to half-open
        minimum-number-of-calls: 5        # Minimum number of calls before evaluating the failure rate

# Resilience4j Timeout Properties
  timelimiter:
    instances:
      inventory:
        timeout-duration: # Specifies the timeout configuration for this instance
          seconds: 3             # Timeout duration set to 3 seconds

# Resilience4j Retry Properties
  retry:
    instances:
      inventory:
        max-attempts: 3        # Maximum number of retry attempts
        wait-duration:         # Time to wait between retry attempts
          seconds: 5           # Wait duration set to 5 seconds
